name: PHP CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 設置 PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0.23'  # 改為您的項目兼容的版本
        extensions: mbstring, intl, pdo_mysql
        
    - name: 安裝依賴
      run: composer install --prefer-dist --no-progress
      
    - name: 複製環境設定
      run: cp .env.example .env
      
    - name: 生成應用程式金鑰
      run: php artisan key:generate
      
    - name: 執行測試
      run: vendor/bin/phpunit

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
    
    steps:
    - uses: actions/checkout@v3
      
    # 除錯步驟: 先測試SSH連接
    - name: 測試SSH連接
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          echo "成功連接到伺服器"
          whoami
          pwd
          ls -la
          if [ -d "${{ secrets.REMOTE_DIR }}" ]; then 
            echo "${{ secrets.REMOTE_DIR }} 目錄存在"
            cd ${{ secrets.REMOTE_DIR }}
            echo "目錄內容:"
            ls -la
            if [ -d ".git" ]; then
              echo "Git 儲存庫存在"
              git remote -v
            else
              echo "Git 儲存庫不存在"
            fi
          else
            echo "${{ secrets.REMOTE_DIR }} 目錄不存在"
          fi

    # 方法1: 使用SSH部署到VPS/專用伺服器
    - name: 使用SSH部署到伺服器
      if: success()
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd ${{ secrets.REMOTE_DIR }}
          git pull origin master
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
        
    # 方法2已移除: 使用FTP部署到共享主機