name: PHP CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 設置 PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0.23'  # 改為您的項目兼容的版本
        extensions: mbstring, intl, pdo_mysql
        
    - name: 安裝依賴
      run: composer install --prefer-dist --no-progress
      
    - name: 複製環境設定
      run: cp .env.example .env
      
    - name: 生成應用程式金鑰
      run: php artisan key:generate
      
    - name: 執行測試
      run: vendor/bin/phpunit

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
    
    steps:
    - uses: actions/checkout@v3
      
    # 使用密碼驗證代替SSH金鑰
    - name: 使用密碼進行SSH連接
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          echo "測試連接"
          whoami
          pwd
          echo "目前目錄:"
          ls -la

    # 部署到伺服器 - 使用密碼驗證
    - name: 使用密碼部署到伺服器
      if: success()
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          # 檢查和創建目錄
          if [ ! -d "${{ secrets.REMOTE_DIR }}" ]; then
            echo "創建目錄 ${{ secrets.REMOTE_DIR }}"
            mkdir -p ${{ secrets.REMOTE_DIR }}
          fi
          
          cd ${{ secrets.REMOTE_DIR }}
          
          # 檢查是否為git儲存庫
          if [ ! -d ".git" ]; then
            echo "初始化git儲存庫"
            git init
            git remote add origin https://github.com/a620906209/testSomething.git
          fi
          
          # 更新代碼和部署
          git fetch --all
          git reset --hard origin/master
          composer install --no-dev --optimize-autoloader
          
          # 如果.env文件不存在則創建
          if [ ! -f ".env" ]; then
            cp .env.example .env
            php artisan key:generate
          fi
          
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
        
    # 方法2已移除: 使用FTP部署到共享主機